# fly.toml app configuration file generated for arxiv-hype on 2023-05-27T10:11:15-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "arxiv-hype"
primary_region = "ewr"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"
  TORCH_HOME = "models/pytorch_hub"

[http_service]
  processes = ["web"]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[processes]
  web = "gunicorn -k uvicorn.workers.UvicornWorker main:fastapi_app"

# [mounts]
#  source="arxiv_hype_data"
#  destination="/persistent_vol"