name: update-db
run-name: Pull new data and update databases.
# on: [workflow_dispatch]
on:
  schedule:
    - cron: "0 9 * * *"
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:    
    - name: Invoke update hook
      uses: distributhor/workflow-webhook@v3
      env:
        webhook_url: ${{ secrets.WEBHOOK_URL }}
        webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
